"""Drift gate for generated docs: CAPABILITY_MATRIX.md, features.json, docs/tools/.

These are generated from docs/tools/MCP_CATALOG.json (by gen_capability_matrix.py /
gen_features_json.py) and from the tool sources themselves (gen_tool_inventory.py).
If a source changes and someone forgets to regenerate, these docs silently rot —
teaching humans, search engines, and AI agents a stale tool surface. This test
makes "forgot to regenerate" a red build.

On failure: run
    python bin/gen_capability_matrix.py
    python bin/gen_features_json.py
    python bin/gen_tool_inventory.py
and commit the regenerated files.
"""
from __future__ import annotations

import hashlib
import json
import os
import pathlib
import re
import sys

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_BIN = os.path.join(_ROOT, "bin")
if _BIN not in sys.path:
    sys.path.insert(0, _BIN)


def _read(path: str) -> str:
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def test_capability_matrix_is_fresh(tmp_path, monkeypatch):
    committed = os.path.join(_ROOT, "docs", "CAPABILITY_MATRIX.md")
    assert os.path.exists(committed), "CAPABILITY_MATRIX.md missing — run gen_capability_matrix.py"

    import gen_capability_matrix
    # Redirect the generator's output to a temp file, then compare content.
    fresh = tmp_path / "CAPABILITY_MATRIX.md"
    monkeypatch.setattr(gen_capability_matrix, "OUTPUT", str(fresh))
    gen_capability_matrix.main()

    assert _read(committed) == _read(str(fresh)), (
        "CAPABILITY_MATRIX.md is stale — run `python bin/gen_capability_matrix.py` and commit."
    )


def test_features_json_is_fresh(tmp_path, monkeypatch):
    committed = os.path.join(_ROOT, "docs", "features.json")
    assert os.path.exists(committed), "features.json missing — run gen_features_json.py"

    import gen_features_json
    fresh = tmp_path / "features.json"
    monkeypatch.setattr(gen_features_json, "OUTPUT", str(fresh))
    gen_features_json.main()

    # Compare parsed objects so insignificant whitespace never false-fails.
    assert json.loads(_read(committed)) == json.loads(_read(str(fresh))), (
        "features.json is stale — run `python bin/gen_features_json.py` and commit."
    )


def test_features_json_tool_count_matches_catalog():
    """features.json's tool count must equal the catalog's — a cheap independent
    check that doesn't depend on the generator running."""
    catalog = json.loads(_read(os.path.join(_ROOT, "docs", "tools", "MCP_CATALOG.json")))
    features = json.loads(_read(os.path.join(_ROOT, "docs", "features.json")))
    assert features["tools"]["total"] == len(catalog["tools"]), (
        "features.json tool count != catalog tool count — regenerate features.json."
    )


# ── docs/tools/*.md — per-tool pages generated by gen_tool_inventory.py ──────
#
# Each page carries `tool:` and `sha1:` front-matter naming the source it was
# generated from. That makes staleness checkable WITHOUT re-running the
# generator (which is slow and rewrites mtimes), so these stay cheap enough to
# run on every build.
#
# This gap is why 17 pages drifted unnoticed: the two tests above cover
# catalog-derived docs only, so a tool source could change with no gate at all.
# chatlog_prune.py's sha1 moved on 2026-08-09 and the page was still describing
# the older source days later.

_TOOLS_DIR = pathlib.Path(_ROOT) / "docs" / "tools"
_FRONT_TOOL = re.compile(r"^tool:\s*(\S+)", re.M)
_FRONT_SHA1 = re.compile(r"^sha1:\s*([0-9a-f]+)", re.M)


def _tool_pages():
    """(page, declared_source, declared_sha1) for every generated tool page."""
    for md in sorted(_TOOLS_DIR.glob("*.md")):
        if md.name in {"INDEX.md", "MCP_CATALOG.json"}:
            continue
        head = md.read_text(encoding="utf-8", errors="replace")[:400]
        m_tool, m_sha = _FRONT_TOOL.search(head), _FRONT_SHA1.search(head)
        if m_tool and m_sha:
            yield md, pathlib.Path(_ROOT) / m_tool.group(1), m_sha.group(1)


def test_tool_pages_are_fresh():
    """No page may describe a source that has changed since it was generated."""
    stale = []
    for md, src, declared in _tool_pages():
        if not src.exists():
            continue  # covered by the orphan test below
        # Normalise CRLF exactly as gen_tool_inventory.file_sha1 does: the hash
        # must describe CONTENT, not the checkout's line endings, or a page
        # generated on Windows can never match on a Linux CI runner.
        _content = src.read_bytes().replace(b"\r\n", b"\n")
        actual = hashlib.sha1(_content).hexdigest()[: len(declared)]
        if actual != declared:
            stale.append(f"{md.name} (declares {declared}, source is {actual})")
    assert not stale, (
        "Stale tool pages — run `python bin/gen_tool_inventory.py` and commit:\n  "
        + "\n  ".join(stale)
    )


def test_no_orphaned_tool_pages():
    """A page whose source no longer exists must be deleted.

    The generator only writes; it never removes. So a deleted or relocated tool
    leaves its page behind, documenting something that is gone — worse than no
    page, because it reads as current. Caught two on 2026-08-11:
    test_knowledge.py was deleted outright and test_sqlite_pragmas.py moved to
    tests/, both leaving stale pages for months.
    """
    orphans = [
        f"{md.name} -> {src.relative_to(_ROOT).as_posix()}"
        for md, src, _ in _tool_pages()
        if not src.exists()
    ]
    assert not orphans, (
        "Orphaned tool pages (source is gone) — delete them:\n  " + "\n  ".join(orphans)
    )
